# Security first
sudo: false

# Hatch latest pythons
language: python
python:
  - "3.5"

# Set ENV to use TensorFlow
before_install:
#  - export KERAS_BACKEND=tensorflow

# Batch install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py

# Install non-pip dependencies
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
mkdir build
cd build
cmake .. 
make -j 

# Run unit tests
script: 
  - echo true
