# Security first
sudo: false

# Hatch latest pythons
language: python
python:
  - "3.5"
  - "nightly"
  - "pypy3"

# batch install dependencies
install:
  - pip install --user -r requirements.txt
  - python setup.py
